apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendatahub

bases:
- ../../base

# Override namespace
namespace: opendatahub

# Patch for OpenDataHub/RHOAI specific configuration
patchesStrategicMerge:
- configmap-patch.yaml
- deployment-patch.yaml

resources:
- ../../base/route.yaml

commonLabels:
  opendatahub.io/component: "true"
  app.kubernetes.io/part-of: opendatahub
