apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

# Patch for standard Kubernetes
patchesStrategicMerge:
- configmap-patch.yaml

resources:
- ../../base/ingress.yaml

commonLabels:
  environment: production
